- hosts: "docker_to_traefik"
  become: yes
  vars_files:
    - "group_vars/secrets.yml"
    - "group_vars/traifik.yml"
  tasks:
    - name: Ensure OS dependencies are installed.
      package:
        name:
          - sudo
          - rsync
          - python3
          - python3-pip
          - python3-docker
          - python3-jsondiff
          - python3-yaml
          # - python3-pyyaml-env-tag
        state: present
    
    - name: "Install docker"
      include_role:
        name: "docker"
    
    - name: "Swarm init"
      include_role:
        name: "swarm_init"

    - name: "Install portainer"
      include_role:
        name: "portainer"

    # - name: "Deploy traefik"
    #   include_role:
    #     name: traefik
