---
#Get info about swarm 
- name: Get info on Docker Swarm
  docker_swarm_info:
    nodes: yes
  ignore_errors: yes
  register: result

- name: Count nodes in Swarm
  when:
    - result.docker_swarm_active is true
    - result.docker_swarm_manager is true
  set_fact:
    swarm_nodes_count: "{{ result.nodes | length }}"

- name: Stack swarm info
  debug:
    msg: |
      Was able to talk to docker daemon: {{ result.can_talk_to_docker }}
      Docker in Swarm mode: {{ result.docker_swarm_active }}
      This is a Manager node: {{ result.docker_swarm_manager }}