{
 "title": "Light",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host CSV Uploader",
    "query": {
     "query": "label_values(vertx_http_server_active_connections{application=\"csv-uploader\"}, instance)"
    }
   },
   {
    "name": "nodepodd",
    "label": "Host PODD adapter",
    "query": {
     "query": "label_values(queryrequestworker_req_count_total{application=\"podd-adapter-query\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HealthCheck",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Liveness",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fieldConfig": {
      "defaults": {},
      "overrides": []
     },
     "expr": "liveness{application=\"csv-uploader\", instance=\"$node\"}",
     "legendFormat": "Liveness"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "fieldConfig": {
      "defaults": {},
      "overrides": []
     },
     "expr": "readiness{application=\"csv-uploader\", instance=\"$node\"}",
     "legendFormat": "Readiness"
    }
   ]
  },
  {
   "title": "CSV uploader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP success",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "fieldConfig": {
      "defaults": {},
      "overrides": []
     },
     "expr": "rate(vertx_http_server_requests_total{code=\"200\", method != \"GET\", instance=\"$node\"}[$__rate_interval])*8"
    }
   ]
  },
  {
   "title": "HTTP unsuccess",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "fieldConfig": {
      "defaults": {},
      "overrides": []
     },
     "expr": "(sum(rate(vertx_http_server_requests_total{code=~\"500|400\", method != \"GET\", instance=\"$node\"}[$__rate_interval])*8)/sum(rate(vertx_http_server_requests_total{code=~\"500|400|200\", method != \"GET\", instance=\"$node\"}[$__rate_interval])*8))*100",
     "legendFormat": "Percent unsuccess"
    }
   ]
  },
  {
   "title": "HTTP AVG&MAX time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "fieldConfig": {
      "defaults": {},
      "overrides": []
     },
     "expr": "sum(rate(vertx_http_server_response_time_seconds_sum{ method!= \"GET\",instance=\"$node\"}[$__rate_interval])*8)/sum(rate(vertx_http_server_response_time_seconds_count{ method != \"GET\", instance=\"$node\"}[$__rate_interval])*8)",
     "legendFormat": "AVG time"
    },
    {
     "fieldConfig": {
      "defaults": {},
      "overrides": []
     },
     "expr": "max(vertx_http_server_response_time_seconds_max{method != \"GET\", instance=\"$node\"})",
     "legendFormat": "MAX time"
    }
   ]
  },
  {
   "title": "PODD adapter query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "QUERY.RQ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "fieldConfig": {
      "defaults": {},
      "overrides": []
     },
     "expr": "rate(queryrequestworker_req_count_total{instance=\"$nodepodd\"}[$__rate_interval])*8",
     "legendFormat": "query.rq"
    }
   ]
  },
  {
   "title": "QUERY.RQ Verticle MAX&AVG",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "fieldConfig": {
      "defaults": {},
      "overrides": []
     },
     "expr": "sum(rate(queryrequestworker_req_time_seconds_sum{ instance=\"$nodepodd\"}[$__rate_interval])*8)/sum(rate(queryrequestworker_req_time_seconds_count{instance=\"$nodepodd\"}[$__rate_interval])*8)",
     "legendFormat": "AVG time"
    },
    {
     "fieldConfig": {
      "defaults": {},
      "overrides": []
     },
     "expr": "max(queryrequestworker_req_time_seconds_max{instance=\"$nodepodd\"})",
     "legendFormat": "MAX time"
    }
   ]
  }
 ]
}