{
 "title": "Site availability RPN",
 "tags": [ "sites" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(probe_success{job=~\"blackbox-http.+\"}, instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Up/Down Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Site availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SSL Cert Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 11 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$instance\"}-time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Probe HTTP  duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$instance\",phase=\"connect\"}",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "probe_http_duration_seconds{instance=~\"$instance\",phase=\"processing\"}",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "probe_http_duration_seconds{instance=~\"$instance\",phase=\"resolve\"}",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "probe_http_duration_seconds{instance=~\"$instance\",phase=\"tls\"}",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "probe_http_duration_seconds{instance=~\"$instance\",phase=\"transfer\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}