{
 "title": "Summary RPN",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db",
    "label": "Db",
    "query": {
     "query": "label_values(pgbouncer_databases_current_connections,database)"
    }
   },
   {
    "name": "mode",
    "label": "Mode",
    "query": {
     "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pools Connections PgBouncer",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pools_client_active_connections{database=~\"$db\"}",
     "legendFormat": "Client active connections "
    },
    {
     "expr": "pgbouncer_pools_client_waiting_connections{database=~\"$db\"}",
     "legendFormat": "Client waiting connections"
    },
    {
     "expr": "pgbouncer_pools_server_active_connections{database=~\"$db\"}",
     "legendFormat": "Server active connections"
    },
    {
     "expr": "pgbouncer_pools_server_idle_connections{database=~\"$db\"}",
     "legendFormat": "Server idle connections"
    },
    {
     "expr": "pgbouncer_pools_server_used_connections{database=~\"$db\"}",
     "legendFormat": "Server used connections"
    },
    {
     "expr": "pgbouncer_pools_server_testing_connections{database=~\"$db\"}",
     "legendFormat": "Server testing connections"
    },
    {
     "expr": "pgbouncer_pools_server_login_connections{database=~\"$db\"}",
     "legendFormat": "Server login connections"
    },
    {
     "expr": "pgbouncer_databases_current_connections{database=~\"$db\"}",
     "legendFormat": "Database current connections"
    }
   ]
  },
  {
   "title": "Transactions PostgreSQL",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{datname=~\"$db\"}[5m])",
     "legendFormat": " {{instance}} {{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{datname=~\"$db\"}[5m])",
     "legendFormat": " {{instance}} {{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Lock tables PostgreSQL",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$db\", mode=~\"$mode\"} != 0",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Replica's Write lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_stat_replica_lag_lag", "legendFormat": "Replica:{{client}}" }
   ]
  }
 ]
}