{
 "title": "СМЭВ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "NEW SMEV message processing",
   "type": "graph",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(rpn_smev_messages_count[2m])",
     "legendFormat": "{{field}}"
    }
   ]
  },
  {
   "title": "SMEV message processing",
   "type": "graph",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(rosprirodnadzor_smev_messages_processing[2m])",
     "legendFormat": "{{indicator}}"
    }
   ]
  },
  {
   "title": "HORIZON queue throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rosprirodnadzor_horizon_queue_throughput",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "HORIZON jobs by type",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 10, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rosprirodnadzor_horizon_jobs_by_type",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}