---
- name: Create config docker
  when: docker_daemon_options is defined
  block:
    - name: Ensure /etc/docker/ directory exists.
      file:
        path: /etc/docker
        state: directory
        mode: 0755

    - name: Configure Docker daemon options.
      when: docker_daemon_options.keys() | length > 0
      copy:
        content: "{{ docker_daemon_options | to_nice_json }}"
        dest: /etc/docker/daemon.json
        mode: 0644
      notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "started"
    enabled: "true"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- name: Ensure docker users are added to the docker group.
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

