---
- name: Ensure dependencies are installed.
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - curl
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Add Docker apt key.
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: "true"

- name: Add Docker apt key (alternative for older systems without SNI).
  when: add_repository_key is failed
  block:
    - name: Ensure curl is present (on older systems without SNI).
      package: name=curl state=present

    - name: Add Docker apt key.
      shell: >
        curl -sSL https://download.docker.com/linux/debian/gpg | apt-key add -
      args:
        warn: false

- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    state: present
    update_cache: true

- name: Add docker packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest

- name: Add the user '{{ ansible_user }}' to group 'docker'
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes