---

- name: Ensure dependencies are installed.
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - curl
      - python3
      - python3-pip
      - python3-venv
      - docker.io
      - docker-compose

- name: Add the user '{{ ansible_user }}' to group 'docker'
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    group: docker
    append: yes